### ISSUE TITLE
How to mirror video?

### ISSUE THREAD

**Issue by Lenne231** [Temasys/AdapterJS#218]
Is there a way to mirror the video when using the WebRTC plugin? Currently it's very easy to do this with a `video` element but it doesn't seem to be possible when using the plugin.

```css
#video
{
    transform: rotateY(180deg);
    -webkit-transform:rotateY(180deg);
    -moz-transform:rotateY(180deg);
}
```
